# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe703bc0b71cd27012403327245af90aa7adf188df30ed8ebb757e43dafe4e8203c98055f1d18f93ec5d7bc0da058203215d35bd07415a504c1bfc3debd1f0ec

test:
  secret_key_base: 0bf8a0a23d6e5a53aad6855d6cc150b25ca1ec09bfc0a443b035e802f5f9c02b99f2a6b6cfe88018fd78fb1f00254eb82716055902b524771bc7bd3d1c777172

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
